#!/usr/bin/env python3
import json

lent_data = {
  'lent': {
    '1': {
      '0': {'title': '1st Sunday Lent Orthodoxy', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 11, 'verses': '24-26, 32-12:2a', 'text': '', 'context': 'Hebrews 11:24-26, 32-12:2a'}, {'type': 'gospel', 'book': 'John', 'chapter': 1, 'verses': '43-51', 'text': '', 'context': 'John 1:43-51'}]},
      '1': {'title': '1st Monday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 1, 'verses': '1-20', 'text': '', 'context': 'Isaiah 1:1-20 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 1, 'verses': '1-13', 'text': '', 'context': 'Genesis 1:1-13 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 1, 'verses': '1-20', 'text': '', 'context': 'Proverbs 1:1-20 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 1, 'verses': '1-12', 'text': '', 'context': 'Hebrews 1:1-12'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 2, 'verses': '23-3:5', 'text': '', 'context': 'Mark 2:23-3:5'}]},
      '2': {'title': '1st Tuesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 1, 'verses': '19-2:3', 'text': '', 'context': 'Isaiah 1:19-2:3 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 1, 'verses': '14-23', 'text': '', 'context': 'Genesis 1:14-23 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 1, 'verses': '20-33', 'text': '', 'context': 'Proverbs 1:20-33 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 2, 'verses': '11-18', 'text': '', 'context': 'Hebrews 2:11-18'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 3, 'verses': '23-27', 'text': '', 'context': 'Mark 3:23-27'}]},
      '3': {'title': '1st Wednesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 2, 'verses': '3-11', 'text': '', 'context': 'Isaiah 2:3-11 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 1, 'verses': '24-2:3', 'text': '', 'context': 'Genesis 1:24-2:3 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 2, 'verses': '1-21', 'text': '', 'context': 'Proverbs 2:1-21 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 2, 'verses': '2-10', 'text': '', 'context': 'Hebrews 2:2-10'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 3, 'verses': '28-35', 'text': '', 'context': 'Mark 3:28-35'}]},
      '4': {'title': '1st Thursday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 2, 'verses': '11-21', 'text': '', 'context': 'Isaiah 2:11-21 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 2, 'verses': '4-19', 'text': '', 'context': 'Genesis 2:4-19 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 3, 'verses': '1-18', 'text': '', 'context': 'Proverbs 3:1-18 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 3, 'verses': '12-16', 'text': '', 'context': 'Hebrews 3:12-16'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 4, 'verses': '24-34', 'text': '', 'context': 'Mark 4:24-34'}]},
      '5': {'title': '1st Friday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 3, 'verses': '1-14', 'text': '', 'context': 'Isaiah 3:1-14 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 2, 'verses': '20-3:20', 'text': '', 'context': 'Genesis 2:20-3:20 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 3, 'verses': '19-34', 'text': '', 'context': 'Proverbs 3:19-34 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 4, 'verses': '1-13', 'text': '', 'context': 'Hebrews 4:1-13'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 5, 'verses': '24-34', 'text': '', 'context': 'Mark 5:24-34'}]},
      '6': {'title': '1st Saturday Lent: St Theodore the Recruit', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 1, 'verses': '1-12', 'text': '', 'context': 'Hebrews 1:1-12'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 2, 'verses': '23-3:5', 'text': '', 'context': 'Mark 2:23-3:5'}, {'type': 'epistle', 'book': '2 Timothy', 'chapter': 2, 'verses': '1-10', 'text': '', 'context': '2 Timothy 2:1-10'}, {'type': 'gospel', 'book': 'John', 'chapter': 15, 'verses': '17-16:2', 'text': '', 'context': 'John 15:17-16:2'}]}
    },
    '2': {
      '0': {'title': '2nd Sunday Lent: St Gregory Palamas', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 1, 'verses': '10-2:3', 'text': '', 'context': 'Hebrews 1:10-2:3'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 2, 'verses': '1-12', 'text': '', 'context': 'Mark 2:1-12'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 7, 'verses': '26-8:2', 'text': '', 'context': 'Hebrews 7:26-8:2'}, {'type': 'gospel', 'book': 'John', 'chapter': 10, 'verses': '9-16', 'text': '', 'context': 'John 10:9-16'}]},
      '1': {'title': '2nd Monday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 4, 'verses': '2-6; 5:1-7', 'text': '', 'context': 'Isaiah 4:2-6; 5:1-7 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 3, 'verses': '21-4:7', 'text': '', 'context': 'Genesis 3:21-4:7 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 3, 'verses': '34-4:22', 'text': '', 'context': 'Proverbs 3:34-4:22 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 6, 'verses': '9-12', 'text': '', 'context': 'Hebrews 6:9-12'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 6, 'verses': '30-45', 'text': '', 'context': 'Mark 6:30-45'}]},
      '2': {'title': '2nd Tuesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 5, 'verses': '7-16', 'text': '', 'context': 'Isaiah 5:7-16 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 4, 'verses': '8-15', 'text': '', 'context': 'Genesis 4:8-15 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 5, 'verses': '1-15', 'text': '', 'context': 'Proverbs 5:1-15 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 6, 'verses': '13-20', 'text': '', 'context': 'Hebrews 6:13-20'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 6, 'verses': '47-7:8', 'text': '', 'context': 'Mark 6:47-7:8'}]},
      '3': {'title': '2nd Wednesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 5, 'verses': '16-25', 'text': '', 'context': 'Isaiah 5:16-25 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 4, 'verses': '16-26', 'text': '', 'context': 'Genesis 4:16-26 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 5, 'verses': '15-6:3', 'text': '', 'context': 'Proverbs 5:15-6:3 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 7, 'verses': '1-6', 'text': '', 'context': 'Hebrews 7:1-6'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 7, 'verses': '24-30', 'text': '', 'context': 'Mark 7:24-30'}]},
      '4': {'title': '2nd Thursday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 6, 'verses': '1-12', 'text': '', 'context': 'Isaiah 6:1-12 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 5, 'verses': '1-24', 'text': '', 'context': 'Genesis 5:1-24 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 6, 'verses': '3-20', 'text': '', 'context': 'Proverbs 6:3-20 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 7, 'verses': '7-17', 'text': '', 'context': 'Hebrews 7:7-17'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 8, 'verses': '1-10', 'text': '', 'context': 'Mark 8:1-10'}]},
      '5': {'title': '2nd Friday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 7, 'verses': '1-14', 'text': '', 'context': 'Isaiah 7:1-14 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 5, 'verses': '32-6:8', 'text': '', 'context': 'Genesis 5:32-6:8 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 6, 'verses': '20-7:1', 'text': '', 'context': 'Proverbs 6:20-7:1 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 8, 'verses': '7-13', 'text': '', 'context': 'Hebrews 8:7-13'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 8, 'verses': '27-31', 'text': '', 'context': 'Mark 8:27-31'}]},
      '6': {'title': '2nd Saturday Lent: Soul Saturday', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 3, 'verses': '12-16', 'text': '', 'context': 'Hebrews 3:12-16'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 1, 'verses': '35-44', 'text': '', 'context': 'Mark 1:35-44'}, {'type': 'epistle', 'book': '1 Corinthians', 'chapter': 15, 'verses': '47-57', 'text': '', 'context': '1 Corinthians 15:47-57'}, {'type': 'gospel', 'book': 'John', 'chapter': 16, 'verses': '5:24-30', 'text': '', 'context': 'John 5:24-30'}]}
    },
    '3': {
      '0': {'title': '3rd Sunday Lent: Veneration of the Cross', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 4, 'verses': '14-5:6', 'text': '', 'context': 'Hebrews 4:14-5:6'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 8, 'verses': '34b-9:1', 'text': '', 'context': 'Mark 8:34b-9:1'}]},
      '1': {'title': '3rd Monday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 8, 'verses': '13-9:7', 'text': '', 'context': 'Isaiah 8:13-9:7 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 6, 'verses': '9-22', 'text': '', 'context': 'Genesis 6:9-22 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 8, 'verses': '1-21', 'text': '', 'context': 'Proverbs 8:1-21 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 9, 'verses': '24-28', 'text': '', 'context': 'Hebrews 9:24-28'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 8, 'verses': '27-31', 'text': '', 'context': 'Mark 8:27-31'}]},
      '2': {'title': '3rd Tuesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 9, 'verses': '9-10:4', 'text': '', 'context': 'Isaiah 9:9-10:4 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 7, 'verses': '1-5', 'text': '', 'context': 'Genesis 7:1-5 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 8, 'verses': '32-9:11', 'text': '', 'context': 'Proverbs 8:32-9:11 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 9, 'verses': '11-14', 'text': '', 'context': 'Hebrews 9:11-14'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 9, 'verses': '17-31', 'text': '', 'context': 'Mark 9:17-31'}]},
      '3': {'title': '3rd Wednesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 10, 'verses': '12-20', 'text': '', 'context': 'Isaiah 10:12-20 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 7, 'verses': '6-9', 'text': '', 'context': 'Genesis 7:6-9 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 9, 'verses': '12-18', 'text': '', 'context': 'Proverbs 9:12-18 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 9, 'verses': '15-23', 'text': '', 'context': 'Hebrews 9:15-23'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 10, 'verses': '2-12', 'text': '', 'context': 'Mark 10:2-12'}]},
      '4': {'title': '3rd Thursday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 11, 'verses': '10-12:2', 'text': '', 'context': 'Isaiah 11:10-12:2 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 7, 'verses': '11-8:4', 'text': '', 'context': 'Genesis 7:11-8:4 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 10, 'verses': '1-22', 'text': '', 'context': 'Proverbs 10:1-22 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 10, 'verses': '1-18', 'text': '', 'context': 'Hebrews 10:1-18'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 10, 'verses': '32-45', 'text': '', 'context': 'Mark 10:32-45'}]},
      '5': {'title': '3rd Friday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 13, 'verses': '2-13', 'text': '', 'context': 'Isaiah 13:2-13 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 8, 'verses': '4-21', 'text': '', 'context': 'Genesis 8:4-21 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 10, 'verses': '31-11:12', 'text': '', 'context': 'Proverbs 10:31-11:12 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 10, 'verses': '19-31', 'text': '', 'context': 'Hebrews 10:19-31'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 10, 'verses': '46-52', 'text': '', 'context': 'Mark 10:46-52'}]},
      '6': {'title': '3rd Saturday Lent: Soul Saturday', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 10, 'verses': '32-38a', 'text': '', 'context': 'Hebrews 10:32-38a'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 2, 'verses': '14-17', 'text': '', 'context': 'Mark 2:14-17'}, {'type': 'epistle', 'book': '1 Corinthians', 'chapter': 15, 'verses': '47-57', 'text': '', 'context': '1 Corinthians 15:47-57'}, {'type': 'gospel', 'book': 'John', 'chapter': 16, 'verses': '5:24-30', 'text': '', 'context': 'John 5:24-30'}]}
    },
    '4': {
      '0': {'title': '4th Sunday Lent: St John Climacus', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 6, 'verses': '13-20', 'text': '', 'context': 'Hebrews 6:13-20'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 9, 'verses': '17-31', 'text': '', 'context': 'Mark 9:17-31'}, {'type': 'epistle', 'book': 'Ephesians', 'chapter': 5, 'verses': '8b-19', 'text': '', 'context': 'Ephesians 5:8b-19'}, {'type': 'gospel', 'book': 'Matthew', 'chapter': 4, 'verses': '25-5:12a', 'text': '', 'context': 'Matthew 4:25-5:12a'}]},
      '1': {'title': '4th Monday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 14, 'verses': '24-32', 'text': '', 'context': 'Isaiah 14:24-32 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 8, 'verses': '21-9:7', 'text': '', 'context': 'Genesis 8:21-9:7 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 11, 'verses': '19-12:6', 'text': '', 'context': 'Proverbs 11:19-12:6 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 11, 'verses': '17-23, 27-31', 'text': '', 'context': 'Hebrews 11:17-23, 27-31'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 11, 'verses': '1-11', 'text': '', 'context': 'Mark 11:1-11'}]},
      '2': {'title': '4th Tuesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 25, 'verses': '1-9', 'text': '', 'context': 'Isaiah 25:1-9 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 9, 'verses': '8-17', 'text': '', 'context': 'Genesis 9:8-17 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 12, 'verses': '8-22', 'text': '', 'context': 'Proverbs 12:8-22 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 11, 'verses': '24-26, 32-40', 'text': '', 'context': 'Hebrews 11:24-26, 32-40'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 11, 'verses': '22-26', 'text': '', 'context': 'Mark 11:22-26'}]},
      '3': {'title': '4th Wednesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 26, 'verses': '21-27:9', 'text': '', 'context': 'Isaiah 26:21-27:9 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 9, 'verses': '18-10:1', 'text': '', 'context': 'Genesis 9:18-10:1 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 12, 'verses': '23-13:9', 'text': '', 'context': 'Proverbs 12:23-13:9 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 12, 'verses': '1-10', 'text': '', 'context': 'Hebrews 12:1-10'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 12, 'verses': '1-12', 'text': '', 'context': 'Mark 12:1-12'}]},
      '4': {'title': '4th Thursday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 28, 'verses': '14-22', 'text': '', 'context': 'Isaiah 28:14-22 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 10, 'verses': '32-11:9', 'text': '', 'context': 'Genesis 10:32-11:9 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 13, 'verses': '19-14:6', 'text': '', 'context': 'Proverbs 13:19-14:6 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 12, 'verses': '25-26, 13:22-25', 'text': '', 'context': 'Hebrews 12:25-26, 13:22-25'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 12, 'verses': '28-37', 'text': '', 'context': 'Mark 12:28-37'}]},
      '5': {'title': '4th Friday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 29, 'verses': '13-23', 'text': '', 'context': 'Isaiah 29:13-23 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 12, 'verses': '1-7', 'text': '', 'context': 'Genesis 12:1-7 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 14, 'verses': '15-26', 'text': '', 'context': 'Proverbs 14:15-26 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '7-16', 'text': '', 'context': 'Hebrews 13:7-16'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 13, 'verses': '1-8', 'text': '', 'context': 'Mark 13:1-8'}]},
      '6': {'title': '4th Saturday Lent: Soul Saturday', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 6, 'verses': '9-12', 'text': '', 'context': 'Hebrews 6:9-12'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 7, 'verses': '31-37', 'text': '', 'context': 'Mark 7:31-37'}, {'type': 'epistle', 'book': '1 Corinthians', 'chapter': 15, 'verses': '47-57', 'text': '', 'context': '1 Corinthians 15:47-57'}, {'type': 'gospel', 'book': 'John', 'chapter': 16, 'verses': '5:24-30', 'text': '', 'context': 'John 5:24-30'}]}
    },
    '5': {
      '0': {'title': '5th Sunday Lent: St Mary of Egypt', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 9, 'verses': '11-14', 'text': '', 'context': 'Hebrews 9:11-14'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 10, 'verses': '32b-45', 'text': '', 'context': 'Mark 10:32b-45'}, {'type': 'epistle', 'book': 'Galatians', 'chapter': 3, 'verses': '23-29', 'text': '', 'context': 'Galatians 3:23-29'}, {'type': 'gospel', 'book': 'Luke', 'chapter': 7, 'verses': '36-50', 'text': '', 'context': 'Luke 7:36-50'}]},
      '1': {'title': '5th Monday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 37, 'verses': '33-38:6', 'text': '', 'context': 'Isaiah 37:33-38:6 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 13, 'verses': '12-18', 'text': '', 'context': 'Genesis 13:12-18 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 14, 'verses': '27-15:4', 'text': '', 'context': 'Proverbs 14:27-15:4 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 13, 'verses': '9-13', 'text': '', 'context': 'Mark 13:9-13'}]},
      '2': {'title': '5th Tuesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 40, 'verses': '18-31', 'text': '', 'context': 'Isaiah 40:18-31 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 15, 'verses': '1-15', 'text': '', 'context': 'Genesis 15:1-15 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 15, 'verses': '7-19', 'text': '', 'context': 'Proverbs 15:7-19 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '7-16', 'text': '', 'context': 'Hebrews 13:7-16'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 13, 'verses': '14-23', 'text': '', 'context': 'Mark 13:14-23'}]},
      '3': {'title': '5th Wednesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 41, 'verses': '4-14', 'text': '', 'context': 'Isaiah 41:4-14 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 17, 'verses': '1-9', 'text': '', 'context': 'Genesis 17:1-9 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 15, 'verses': '20-16:9', 'text': '', 'context': 'Proverbs 15:20-16:9 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 13, 'verses': '24-31', 'text': '', 'context': 'Mark 13:24-31'}]},
      '4': {'title': '5th Thursday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 42, 'verses': '5-16', 'text': '', 'context': 'Isaiah 42:5-16 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 18, 'verses': '20-33', 'text': '', 'context': 'Genesis 18:20-33 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 16, 'verses': '17-17:17', 'text': '', 'context': 'Proverbs 16:17-17:17 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 13, 'verses': '31-14:2', 'text': '', 'context': 'Mark 13:31-14:2'}]},
      '5': {'title': '5th Friday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 45, 'verses': '11-17', 'text': '', 'context': 'Isaiah 45:11-17 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 22, 'verses': '1-18', 'text': '', 'context': 'Genesis 22:1-18 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 17, 'verses': '17-18:5', 'text': '', 'context': 'Proverbs 17:17-18:5 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 14, 'verses': '3-9', 'text': '', 'context': 'Mark 14:3-9'}]},
      '6': {'title': '5th Saturday Lent: Akathist', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 9, 'verses': '24-28', 'text': '', 'context': 'Hebrews 9:24-28'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 8, 'verses': '27-31', 'text': '', 'context': 'Mark 8:27-31'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 9, 'verses': '1-7', 'text': '', 'context': 'Hebrews 9:1-7'}, {'type': 'gospel', 'book': 'Luke', 'chapter': 10, 'verses': '38-42; 11:27-28', 'text': '', 'context': 'Luke 10:38-42; 11:27-28'}]}
    },
    '6': {
      '0': {'title': 'Palm Sunday', 'readings': [{'type': 'epistle', 'book': 'Philippians', 'chapter': 4, 'verses': '4-9', 'text': '', 'context': 'Philippians 4:4-9'}, {'type': 'gospel', 'book': 'John', 'chapter': 12, 'verses': '1-18', 'text': '', 'context': 'John 12:1-18'}]},
      '1': {'title': '6th Monday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 48, 'verses': '17-49:4', 'text': '', 'context': 'Isaiah 48:17-49:4 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 27, 'verses': '1-41', 'text': '', 'context': 'Genesis 27:1-41 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 19, 'verses': '16-25', 'text': '', 'context': 'Proverbs 19:16-25 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 14, 'verses': '10-42', 'text': '', 'context': 'Mark 14:10-42'}]},
      '2': {'title': '6th Tuesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 49, 'verses': '6-10', 'text': '', 'context': 'Isaiah 49:6-10 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 31, 'verses': '3-16', 'text': '', 'context': 'Genesis 31:3-16 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 21, 'verses': '3-21', 'text': '', 'context': 'Proverbs 21:3-21 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 14, 'verses': '43-15:1', 'text': '', 'context': 'Mark 14:43-15:1'}]},
      '3': {'title': '6th Wednesday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 58, 'verses': '1-11', 'text': '', 'context': 'Isaiah 58:1-11 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 43, 'verses': '26-45:16', 'text': '', 'context': 'Genesis 43:26-45:16 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 21, 'verses': '23-22:4', 'text': '', 'context': 'Proverbs 21:23-22:4 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 15, 'verses': '1-15', 'text': '', 'context': 'Mark 15:1-15'}]},
      '4': {'title': '6th Thursday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 65, 'verses': '8-16', 'text': '', 'context': 'Isaiah 65:8-16 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 46, 'verses': '1-7', 'text': '', 'context': 'Genesis 46:1-7 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 23, 'verses': '15-24:5', 'text': '', 'context': 'Proverbs 23:15-24:5 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 15, 'verses': '22, 25, 33-41', 'text': '', 'context': 'Mark 15:22, 25, 33-41'}]},
      '5': {'title': '6th Friday Lent', 'readings': [{'type': 'sixth_hour', 'book': 'Isaiah', 'chapter': 66, 'verses': '10-24', 'text': '', 'context': 'Isaiah 66:10-24 Sixth Hour'}, {'type': 'vespers', 'book': 'Genesis', 'chapter': 49, 'verses': '33-50:26', 'text': '', 'context': 'Genesis 49:33-50:26 Vespers'}, {'type': 'vespers', 'book': 'Proverbs', 'chapter': 31, 'verses': '8-31', 'text': '', 'context': 'Proverbs 31:8-31 Vespers'}, {'type': 'epistle', 'book': 'Hebrews', 'chapter': 13, 'verses': '17-21', 'text': '', 'context': 'Hebrews 13:17-21'}, {'type': 'gospel', 'book': 'Mark', 'chapter': 15, 'verses': '43-47', 'text': '', 'context': 'Mark 15:43-47'}]}
    },
    'holy_week': {
      'lazarus': {'title': 'Lazarus Saturday', 'readings': [{'type': 'epistle', 'book': 'Hebrews', 'chapter': 12, 'verses': '28-13:8', 'text': '', 'context': 'Hebrews 12:28-13:8'}, {'type': 'gospel', 'book': 'John', 'chapter': 11, 'verses': '1-45', 'text': '', 'context': 'John 11:1-45'}]},
      'palm': {'title': 'Palm Sunday', 'readings': [{'type': 'epistle', 'book': 'Philippians', 'chapter': 4, 'verses': '4-9', 'text': '', 'context': 'Philippians 4:4-9'}, {'type': 'gospel', 'book': 'John', 'chapter': 12, 'verses': '1-18', 'text': '', 'context': 'John 12:1-18'}], 'vespers_paramia': [{'book': 'Genesis', 'chapter': 49, 'verses': '1-2, 8-12', 'text': '', 'context': 'Genesis 49:1-2, 8-12'}, {'book': 'Zephaniah', 'chapter': 3, 'verses': '14-19', 'text': '', 'context': 'Zephaniah 3:14-19'}, {'book': 'Zechariah', 'chapter': 9, 'verses': '9-15', 'text': '', 'context': 'Zechariah 9:9-15'}], 'matins_gospel': {'book': 'Matthew', 'chapter': 21, 'verses': '1-11, 15-17', 'text': '', 'context': 'Matthew 21:1-11, 15-17'}}
    }
  },
  'fixed': {
    'transfiguration': {'title': 'Transfiguration Aug 6', 'readings': [{'type': 'epistle', 'book': '2 Peter', 'chapter': 1, 'verses': '10-19', 'text': '', 'context': '2 Peter 1:10-19'}, {'type': 'gospel', 'book': 'Matthew', 'chapter': 17, 'verses': '1-9', 'text': '', 'context': 'Matthew 17:1-9'}], 'vespers_paramia': [{'book': 'Exodus', 'chapter': 24, 'verses': '12-18', 'text': '', 'context': 'Exodus 24:12-18'}, {'book': 'Exodus', 'chapter': 33, 'verses': '11-23; 34:4-6, 8', 'text': '', 'context': 'Exodus 33:11-23; 34:4-6, 8'}, {'book': '1 Kings', 'chapter': 19, 'verses': '3-9, 11-13, 15-16', 'text': '', 'context': '1 Kings 19:3-9, 11-13, 15-16'}], 'matins_gospel': {'book': 'Luke', 'chapter': 9, 'verses': '28b-36', 'text': '', 'context': 'Luke 9:28b-36'}}
  }
}

with open('scripture_readings.json', 'r') as f:
    existing = json.load(f)

for sec, items in lent_data.items():
    if sec not in existing:
        existing[sec] = {}
    existing[sec].update(items)

with open('scripture_readings.json', 'w') as f:
    json.dump(existing, f, indent=2)

print('Lent/Holy populated.')
